package main

import (
	"gloo-server/api"
	"gloo-server/socket"
	"log"

	_ "github.com/jinzhu/gorm/dialects/mysql"
	"github.com/swaggo/gin-swagger"
	// _ "github.com/swaggo/gin-swagger/example/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/swaggo/gin-swagger/swaggerFiles"
)

// @title Swagger Example API
// @version 1.0
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host petstore.swagger.io
// @BasePath /v2
func main() {
	r := api.NewRouter()
	// s := &http.Server{
	// 	Addr:           ":8000",
	// 	Handler:        r,
	// 	ReadTimeout:    10 * time.Second,
	// 	WriteTimeout:   10 * time.Second,
	// 	MaxHeaderBytes: 1 << 20,
	// }
	log.Println("Server starting")
	socket.LauchNetServer()

	// use ginSwagger middleware to
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	r.Run(":8000")
}
